### ISSUE TITLE
Schema name being concatinated instead of replaced

### ISSUE THREAD

**Issue by M4Al** [microsoft/dbt-fabric#162]
I have a normal profile with a specific schema mentioned 'silver'

```
fabric-mpl-test:
  target: fabric-mpl-test
  outputs:
    fabric-mpl-test:
      authentication: CLI
      database: DWH
      driver: ODBC Driver 18 for SQL Server
      host: <<EZMOVED>>
      schema: silver
      threads: 4
      type: fabric

```
In my model I add some config to write it away in another schema

`{{ config(
    materialized="table",
    schema="gold"
) }}
`

The result is that a table is created **silver_gold.dimFinancialCompanyName** instead of the expected **gold.dimFinancialCompanyName**.

Not sure if this is an adapter issue of a core dbt feature though.
