### ISSUE TITLE
Schemas not being created in other warehouses, only the one set specified in the profiles.yml.

### ISSUE THREAD

**Issue by Analyticminder** [microsoft/dbt-fabric#166]
Hello, it appears that schemas are not being created when dbt allows the deployment to different warehouses. For example, my `profiles.yml` is set to schema `dbo` and the database is `WH_Stage_Bronze`

```yml
dbt_fabric_testing:
  target: dev
  outputs:
    dev:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: '<your_server>'
      port: 1433
      database: WH_Stage_Bronze
      schema: dbo
      authentication: ActiveDirectoryInteractive
      user: '<your_username>'
      schema_authorization: dbo
```

I have an override for the `generate_database_name.sql` that works successfully in deploying objects to other warehouses in the same workspace (provided the schemas are setup beforehand hence the issue I'm having)

```sql
{% macro generate_database_name(custom_database_name, node) %}
    {% set default_database = target.database %}
    
    {% if (target.name == 'dev') and node.name[:3] == 'STG' %}
        {{"WH_Stage_Bronze"}}
    {% elif (target.name == 'dev') and node.name[:3] == 'CFM' %}
        {{"WH_Conformed_Silver"}}
    {% endif %}
{% endmacro %}

```
I also have an override for the schema that is as follows:

```sql
{% macro generate_schema_name(custom_schema_name, node) %}
    {% if not node.unique_id.startswith('model.dbt_artifacts') %}
        {% set default_schema = target.schema %}
        {% set nodelist = node.name.split('_') %}
        {% set custom_schema_name = nodelist[1] %}
        {{ custom_schema_name | trim }}
    {% else %}
        {{ default_schema }}
    {% endif %}
{% endmacro %}

```

It basically parses the file or model name by double underscores. It takes the middle section of the name and uses that as the schema. 
When I "`dbt run`" the project, I get the error:
```
"('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]
The specified schema name "common" either does not exist or you do not have permission to use it. (2760) (SQLMoreResults)')"
```

What should happen is the files that start with `"CFM__"` should go to the warehouse `WH_Conformed_Silver` and files that start with `"STG__"` go to `WH_Stage_Bronze` warehouse. The `"CFM__common"` files should go to the `WH_Conformed_Silver.common` Warehouse/schema and the `"CFM__sales"` should go to the `WH_Conformed_Silver.sales` Warehouse/schema. The only schemas that exist on `WH_Conformed_Silver` at this point is `dbo`. 
![image](https://github.com/microsoft/dbt-fabric/assets/168775156/c041c149-f0ee-4f3a-a041-f7ce387846b1)
However, if I manually create the schemas for `WH_Conformed_Silver`: 
```sql
USE WH_Conformed_Silver;
  CREATE SCHEMA [common];
  CREATE SCHEMA [sales];
```

And then do a 'dbt run' then everything runs successfully as the schemas now exist:
![image](https://github.com/microsoft/dbt-fabric/assets/168775156/4b69a6f2-aa67-4ace-9c14-8907525985fc)
Here is the dbt versions I'm using: 
```
(.venv) PS C:\repos\dbt_fabric_testing> dbt --version
Core:
  - installed: 1.8.0-b2
  - latest: 1.7.13 - Ahead of latest version!
Plugins:
  - fabric: 1.8.3 - Up to date!

```

I am able to successfully perform schema deployment/creation to different databases in dbt-snowflake, I figured we should be able to the same for Fabric as Fabric allows for cross-database querying. For a number of reasons, it would be beneficial for dbt-fabric to create these schemas for us. Could someone please help?
