### ISSUE TITLE
Store Failures flag will generate model w/o failure

### ISSUE THREAD

**Issue by TheBishop-98** [microsoft/dbt-fabric#234]
We are encountering an issue that the --store-failures flag will generate a model even when the test passes. All of my claims test tables are blanks when they should not be created because the tests passed?

Project yaml:
``` yaml

data_tests:
  HMA_DBT_ENTERPRISE:
    +store_failures_as: table
    +database: DataMarts 
    +schema: data_tests

```
Model yaml:
``` yaml

- name: company_id
  description: "{{ doc('acl_companyID')}}"
  data_tests:
    - relationships:
        to: ref('stg_ACL_COMPANIES')
        field: company_id
        config:
          severity: warn
  data_type: varchar(8000)

- name: line_of_coverage_id
  description: "{{ doc('acl_lineOfCoverageID')}}"
  data_tests:
    - relationships:
        to: ref('stg_ACL_LINES_OF_COVERAGE')
        field: line_of_coverage_id
        config:
          severity: warn
  data_type: varchar(8000)

```

![Image](https://github.com/user-attachments/assets/088d92b6-645f-4de0-a580-d6c37d604162)
![Image](https://github.com/user-attachments/assets/5e53365e-d3f6-4a1b-ac07-b0feb6201dce)
