### ISSUE TITLE
Adding a custom database does not create materialisations in the chosen database

### ISSUE THREAD

**Issue by IliasIB** [microsoft/dbt-fabric#53]
### Expected Behaviour
Specifying a custom database (like a warehouse or lakehouse in a workspace) creates the materialisations in the correct database

### Actual Behaviour
Everything gets materialised in the default database that is defined in the profiles.yml

### Steps to reproduce
-- profiles.yml
```
fabric:
  target: dev
  outputs:
    dev:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server'
      server: <workspace connection string>
      port: 1433
      database: jaffle_shop_1
      schema: dbt
      authentication: CLI
```
-- dbt_project.yml
```
models:
  jaffle_shop:
    +database: jaffle_shop_2
```

In this example the jaffle_shop models will be created in jaffle_shop_1 even though I defined them to be in jaffle_shop_2

### Configuration
dbt 1.4.6
Microsoft Fabric Warehouse
ODBC Driver 2018

### Possible Causes
I expect this to be an issue in the dbt-fabric packages since creating tables in different warehouses is possible if I use direct queries to the warehouse.
The following query works perfectly from jaffle_shop_1 for example:
```
CREATE TABLE jaffle_shop_2.dbo.Persons (
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255)
);
```
